### PR TITLE
fix: allow re-runs of cargo publish to crates.io

### LINKED ISSUE #183: Allow re-running publishing crates step after failure
### Describe the feature

When the publish crates workflow fails (or hangs) like this: https://github.com/eclipse-zenoh/zenoh/actions/runs/9592753181/job/26451953639 we are unable to re-run the same workflow with the same version because crates.io won't allow publishing the same version again. The code should be improved to check if the crate version already exists and skip publication. This way we can re-run the release workflow without the need to bump the version and yank the failed one from crates.io

### PR DESCRIPTION
**Pull request by diogomatsubara**
During release process, if something fails during the publication process, we can re-run the workflow skipping the packages that were already published.

Fix #183

### CODE REVIEW

File: src/cargo.ts [hunk 1]
```diff
@@ -368,3 +368,13 @@ export function toDebianVersion(version: string, revision?: number): string {
...
   return `${version.replace("-", "~")}-${revision ?? 1}`;
 }
+
+/**
+ * Check if Package is already published in crates.io
+ * @param package Package to check.
+ */
+export function isPublished(pkg: Package): boolean {
+  // Hackish but crates.io doesn't have a stable api anyway.
+  const published_version = sh(`cargo search ${pkg.name}`).split("\n").at(0).match(/".*"/g).at(0).slice(1, -1);
```
Comment (fuzzypixelz) [inline src/cargo.ts:378]: Use 
```suggestion
  const publishedVersion = sh(`cargo search ${pkg.name}`).split("\n").at(0).match(/".*"/g).at(0).slice(1, -1);
```

File: src/cargo.ts [hunk 2]
```diff
@@ -368,3 +368,13 @@ export function toDebianVersion(version: string, revision?: number): string {
...
+  return published_version === pkg.version;
```
Comment (fuzzypixelz) [inline src/cargo.ts:379]:
```suggestion
  return publishedVersion === pkg.version;
```

**Review by fuzzypixelz — APPROVED** [review]
