### PR TITLE
fix: Add sha256 sum file for eclipse

### LINKED ISSUE #110: Upload `sha256sums.txt` in publish-crates-eclipse action
### Describe the feature

[Previous Zenoh releases uploaded this file](https://download.eclipse.org/zenoh/zenoh-plugin-dds/0.10.1-rc/), but it's not yet implemented as part of the new Release process.

### PR DESCRIPTION
**Pull request by diogomatsubara**
Fix #110

### CODE REVIEW

File: src/publish-crates-eclipse.ts [hunk 1]
```diff
@@ -45,21 +45,24 @@ export async function main(input: Input) {
...
     const results = await artifact.listArtifacts({ latest: true });
     for (const result of results.artifacts) {
       if (shouldPublishArtifact(result.name)) {
         const { downloadPath } = await artifact.downloadArtifact(result.id);
         const archive = path.join(downloadPath, result.name);
-        const archiveDir = `${input.sshHostPath}/${input.version}`;
 
-        core.info(`Uploading ${archive} to download.eclipse.org`);
+        // Write the sha256 checksum of the archive
+        sh(`sha256 ${archive} >> ${checksumFile}`);
```
Comment (fuzzypixelz) [inline src/publish-crates-eclipse.ts:63]: Do we know if this command is available on the GitHub runners? And shouldn't it be `sha256sum`?

There is also a function that does this in [publish-crates-homebrew](https://github.com/eclipse-zenoh/ci/blob/main/src/publish-crates-homebrew.ts#L100). Perhaps it makes sense to put that in a `sha256.ts` module and reuse it.

Comment (diogomatsubara) [reply src/publish-crates-eclipse.ts:63]: Good point! I'll refactor the function available in the publish-crates-homebrew so they can both be used from the same module. Thanks for the review!

**Comment by diogomatsubara** [comment]
Looks like the Eclipse PMI is down so the ECA check is failing.
